class FileStorageObserver(RunObserver):
    VERSION = "FileStorageObserver-0.7.0"
    @classmethod
    def create(cls, *args, **kwargs):
        ...
    def __init__(self, basedir, resource_dir=None, source_dir=None, template=None, priority=DEFAULT_FILE_STORAGE_PRIORITY, copy_artifacts=True, copy_sources=True):
        ...
    def initialize(self, basedir, resource_dir, source_dir, template, priority=DEFAULT_FILE_STORAGE_PRIORITY, copy_artifacts=True, copy_sources=True):
        ...
    @classmethod
    def create_from(cls, *args, **kwargs):
        ...
    def _maximum_existing_run_id(self):
        ...
    def _make_dir(self, _id):
        ...
    def _make_run_dir(self, _id):
        ...
    def queued_event(self, ex_info, command, host_info, queue_time, config, meta_info, _id):
        ...
    def save_sources(self, ex_info):
        ...
    def started_event(self, ex_info, command, host_info, start_time, config, meta_info, _id):
        ...
    def find_or_save(self, filename, store_dir: Path):
        ...
    def save_json(self, obj, filename):
        ...
    def save_file(self, filename, target_name=None):
        ...
    def save_cout(self):
        ...
    def render_template(self):
        ...
    def heartbeat_event(self, info, captured_out, beat_time, result):
        ...
    def completed_event(self, stop_time, result):
        ...
    def interrupted_event(self, interrupt_time, status):
        ...
    def failed_event(self, fail_time, fail_trace):
        ...
    def resource_event(self, filename):
        ...
    def artifact_event(self, name, filename, metadata=None, content_type=None):
        ...
    def log_metrics(self, metrics_by_name, info):
        """Store new measurements into metrics.json."""
        ...
    def __eq__(self, other):
        ...

def find_or_save(self, filename, store_dir: Path):
    try:
        Path(filename).resolve().relative_to(Path(self.basedir).resolve())
        is_relative_to = True
    except ValueError:
        is_relative_to = False

    if is_relative_to and not self.copy_artifacts:
        return filename
    else:
        store_dir.mkdir(parents=True, exist_ok=True)
        source_name, ext = os.path.splitext(os.path.basename(filename))
        md5sum = get_digest(filename)
        store_name = source_name + "_" + md5sum + ext
        store_path = store_dir / store_name
        if not store_path.exists():
            copyfile(filename, str(store_path))
        return store_path

def save_json(self, obj, filename):
    with open(os.path.join(self.dir, filename), "w") as f:
        json.dump(flatten(obj), f, sort_keys=True, indent=2)
        f.flush()
